# Site settings
title: Wheat7 Blog
header-img: img/home-bg.jpg
email: 7wheat@gmail.com
copyright_name: Wheat7
description: "Write your site description here. It will be used as your sites meta description as well!"
url: "http://Wheat7"
twitter_username: wheatseven
github_username:  wheat7
facebook_username:  Wheat Steven
email_username:  7wheat@gmail.com
baseurl: ""

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]